rules:
  - p/typescript
  - p/node
  - p/owasp-top-ten
  - p/security-audit

paths:
  include:
    - apps/
    - libs/
  exclude:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/coverage/**"
    - "**/*.spec.ts"
    - "**/*.test.ts"
