sonar.projectKey=TeamOneee_pos-project-be
sonar.organization=teamoneee
sonar.host.url=https://sonarcloud.io
sonar.sources=apps,libs
sonar.tests=apps,libs,test
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.module.ts,**/main.ts
sonar.exclusions=**/dist/**,**/coverage/**,**/node_modules/**,**/*.prisma/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
